name: Check API & Maybe Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  checkapi:
    runs-on: ubuntu-20.04

    outputs:
      new-data: ${{ steps.checkdata.outputs.new-data }}

    steps:

      - name: Set cache key by time
        run: echo "cache-time="`date '+%s'` >> $GITHUB_ENV

      - name: Cache fetched data
        uses: actions/cache@v2
        with:
          path: f1data.json
          key: ${{ runner.os }}-f1data-${{ env.cache-time }}
          restore-keys: |
            ${{ runner.os }}-f1data-

      - name: Fetch new data
        run: curl "https://ergast.com/api/f1/2022/driverStandings.json" -o newf1data.json

      - name: See if new data is different from cached data
        run: diff -q f1data.json newf1data.json

      - name: Overwrite data and set output if data is different
        id: checkdata
        if: ${{ failure() }}
        run: |
          mv newf1data.json f1data.json
          echo "::set-output name=new-data::true"\

      - name: Check completed
        if: ${{ always() }}
        run: echo 'Check completed'

  # build:
  #   needs: checkapi
  #   if: needs.checkapi.outputs.new-data
  #   uses: ./.github/workflows/gh-pages.yml
