name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 17-23 * * 0'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Set timestamp for data cache key
        run: |
          test=`date '+%s'`
          echo "cache_time="$(($test - ($test % (30*60)))) >> $GITHUB_ENV

      - name: Cache fetched data
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-fetched-${{ env.cache_time }}
          restore-keys: |
            ${{ runner.os }}-fetched-

      - name: Run build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
